name: Code Quality
on:
  workflow_dispatch:
  pull_request:
    branches:
      - v6
      - develop-v6
  push:
    branches:
      - v6
      - develop-v6
permissions:
  contents: read
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  ci:
    name: ci
    uses: studioespresso/.github/.github/workflows/ci.yml@main
    with:
      php_version: '8.5'
      craft_version: '6'
      jobs: '["pint", "larastan"]'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
